# https://taskfile.dev/usage/
version: '3'

vars:
  VENV_DIR: ./venv

env:
  PIP_INDEX_URL: https://mirrors.ustc.edu.cn/pypi/web/simple

tasks:
  default:
    desc: create virtual environments
    cmds:
      - python3 -m venv {{.VENV_DIR}}
      - "{{.VENV_DIR}}/bin/pip install -r requirements.txt"
      - echo "use [\$source venv/bin/activate] to activate virtual environment"

  archives-generate:
    desc: Generating distribution archives
    cmds:
      - python3 -m pip install --upgrade build
      - python3 -m build

  archives-upload:
    desc: Uploading the distribution archives
    cmds:
      - python3 -m pip install --upgrade twine
      - python3 -m twine upload --repository pypi dist/*
